name: Security

on:
    workflow_run:
        workflows: [CI]
        types: [completed]
    schedule:
        - cron: "0 6 * * *"
    workflow_dispatch:

permissions:
    contents: read
    security-events: write

defaults:
    run:
        shell: bash

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    audit:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
            - uses: jdx/mise-action@5228313ee0372e111a38da051671ca30fc5a96db # v3.6.3
              with:
                  install: true
                  cache: true
                  github_token: ${{ secrets.GITHUB_TOKEN }}

            - name: Run cargo deny check
              run: cargo deny check

            - name: Run cargo outdated
              run: cargo outdated --depth=1 --exit-code=1
